### ISSUE TITLE
Cannot install the plugin

### ISSUE THREAD

**Issue by shebet** [Sunoo/homebridge-rpi-rf-switch#4]
When I search for this plug in in the Homebridge-x and press install it generates the error below and I cannot install it:
```
USER: pi
DIR: /usr/local/lib
CMD: sudo -E -n npm install homebridge-rpi-rf-switch@latest


> node-calls-python@1.4.0 install /usr/local/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python
> node-gyp rebuild

/bin/sh: 1: python3-config: not found
gyp: Call to 'python3-config --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.51-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-calls-python@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-calls-python@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-07-26T20_32_11_980Z-debug.log

Command failed. Please review log for details.

```

Any idea what to do?

**Comment by Sunoo** [comment]
Do you have Python installed on your device?

**Comment by shebet** [comment]
Yes, 

Here are the versions installed:
`
pi@homebridge:~ $  python --version
Python 2.7.16
pi@homebridge:~ $ python3 --version
Python 3.7.3
`

**Comment by shebet** [comment]
And here is the content of the log file(/home/pi/.npm/_logs/2020-07-26T21_41_45_679Z-debug.log):

`
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'homebridge-rpi-rf-switch@latest'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose npm-session 82d29f1c3f575083
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/homebridge-rpi-rf-switch 1313ms
8 http fetch GET 200 https://registry.npmjs.org/homebridge-rpi-rf-switch/-/homebridge-rpi-rf-switch-2.2.0.tgz 1069ms
9 silly pacote tag manifest for homebridge-rpi-rf-switch@latest fetched in 2480ms
10 timing stage:loadCurrentTree Completed in 2526ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 7ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule homebridge-rpi-rf-switch@2.2.0 checking installable status
18 http fetch GET 304 https://registry.npmjs.org/node-calls-python 143ms (from cache)
19 http fetch GET 304 https://registry.npmjs.org/node-calls-python/-/node-calls-python-1.4.0.tgz 112ms (from cache)
20 silly pacote range manifest for node-calls-python@>=1.4.0 fetched in 278ms
21 silly resolveWithNewModule node-calls-python@1.4.0 checking installable status
22 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 311ms
23 timing stage:loadIdealTree Completed in 326ms
24 silly currentTree lib
25 silly idealTree lib
25 silly idealTree └─┬ homebridge-rpi-rf-switch@2.2.0
25 silly idealTree   └── node-calls-python@1.4.0
26 silly install generateActionsToTake
27 timing stage:generateActionsToTake Completed in 20ms
28 silly diffTrees action count 2
29 silly diffTrees add node-calls-python@1.4.0
30 silly diffTrees add homebridge-rpi-rf-switch@2.2.0
31 silly decomposeActions action count 16
32 silly decomposeActions fetch node-calls-python@1.4.0
33 silly decomposeActions extract node-calls-python@1.4.0
34 silly decomposeActions preinstall node-calls-python@1.4.0
35 silly decomposeActions build node-calls-python@1.4.0
36 silly decomposeActions install node-calls-python@1.4.0
37 silly decomposeActions postinstall node-calls-python@1.4.0
38 silly decomposeActions finalize node-calls-python@1.4.0
39 silly decomposeActions refresh-package-json node-calls-python@1.4.0
40 silly decomposeActions fetch homebridge-rpi-rf-switch@2.2.0
41 silly decomposeActions extract homebridge-rpi-rf-switch@2.2.0
42 silly decomposeActions preinstall homebridge-rpi-rf-switch@2.2.0
43 silly decomposeActions build homebridge-rpi-rf-switch@2.2.0
44 silly decomposeActions install homebridge-rpi-rf-switch@2.2.0
45 silly decomposeActions postinstall homebridge-rpi-rf-switch@2.2.0
46 silly decomposeActions finalize homebridge-rpi-rf-switch@2.2.0
47 silly decomposeActions refresh-package-json homebridge-rpi-rf-switch@2.2.0
48 silly install executeActions
49 silly doSerial global-install 16
50 verbose correctMkdir /home/pi/.npm/_locks correctMkdir not in flight; initializing
51 verbose lock using /home/pi/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
52 silly doParallel extract 2
53 silly extract node-calls-python@1.4.0
54 silly extract homebridge-rpi-rf-switch@2.2.0
55 silly tarball no local data for node-calls-python@>=1.4.0. Extracting by manifest.
56 silly tarball no local data for homebridge-rpi-rf-switch@latest. Extracting by manifest.
57 http fetch GET 304 https://registry.npmjs.org/node-calls-python/-/node-calls-python-1.4.0.tgz 113ms (from cache)
58 silly extract node-calls-python@>=1.4.0 extracted to /usr/local/lib/node_modules/.staging/node-calls-python-ba622f04 (229ms)
59 http fetch GET 304 https://registry.npmjs.org/homebridge-rpi-rf-switch/-/homebridge-rpi-rf-switch-2.2.0.tgz 230ms (from cache)
60 silly extract homebridge-rpi-rf-switch@latest extracted to /usr/local/lib/node_modules/.staging/homebridge-rpi-rf-switch-2404ac90 (273ms)
61 timing action:extract Completed in 286ms
62 silly doReverseSerial unbuild 16
63 silly doSerial remove 16
64 silly doSerial move 16
65 silly doSerial finalize 16
66 silly finalize /usr/local/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python
67 silly finalize /usr/local/lib/node_modules/homebridge-rpi-rf-switch
68 timing action:finalize Completed in 51ms
69 silly doParallel refresh-package-json 2
70 silly refresh-package-json /usr/local/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python
71 silly refresh-package-json /usr/local/lib/node_modules/homebridge-rpi-rf-switch
72 timing action:refresh-package-json Completed in 69ms
73 silly doParallel preinstall 2
74 silly preinstall node-calls-python@1.4.0
75 info lifecycle node-calls-python@1.4.0~preinstall: node-calls-python@1.4.0
76 silly preinstall homebridge-rpi-rf-switch@2.2.0
77 info lifecycle homebridge-rpi-rf-switch@2.2.0~preinstall: homebridge-rpi-rf-switch@2.2.0
78 timing action:preinstall Completed in 9ms
79 silly doSerial build 16
80 silly build node-calls-python@1.4.0
81 info linkStuff node-calls-python@1.4.0
82 silly linkStuff node-calls-python@1.4.0 has /usr/local/lib/node_modules/homebridge-rpi-rf-switch/node_modules as its parent node_modules
83 silly linkStuff node-calls-python@1.4.0 is part of a global install
84 silly linkStuff node-calls-python@1.4.0 is installed into a global node_modules
85 silly build homebridge-rpi-rf-switch@2.2.0
86 info linkStuff homebridge-rpi-rf-switch@2.2.0
87 silly linkStuff homebridge-rpi-rf-switch@2.2.0 has /usr/local/lib/node_modules as its parent node_modules
88 silly linkStuff homebridge-rpi-rf-switch@2.2.0 is part of a global install
89 silly linkStuff homebridge-rpi-rf-switch@2.2.0 is installed into a global node_modules
90 silly linkStuff homebridge-rpi-rf-switch@2.2.0 is installed into the top-level global node_modules
91 timing action:build Completed in 6ms
92 silly doSerial global-link 16
93 silly doParallel update-linked 0
94 silly doSerial install 16
95 silly install node-calls-python@1.4.0
96 info lifecycle node-calls-python@1.4.0~install: node-calls-python@1.4.0
97 verbose lifecycle node-calls-python@1.4.0~install: unsafe-perm in lifecycle true
98 verbose lifecycle node-calls-python@1.4.0~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python/node_modules/.bin:/usr/local/lib/node_modules/homebridge-rpi-rf-switch/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
99 verbose lifecycle node-calls-python@1.4.0~install: CWD: /usr/local/lib/node_modules/homebridge-rpi-rf-switch/node_modules/node-calls-python
100 silly lifecycle node-calls-python@1.4.0~install: Args: [ '-c', 'node-gyp rebuild' ]
101 silly lifecycle node-calls-python@1.4.0~install: Returned: code: 1  signal: null
102 info lifecycle node-calls-python@1.4.0~install: Failed to exec install script
103 timing action:install Completed in 2125ms
104 verbose unlock done using /home/pi/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
105 timing stage:rollbackFailedOptional Completed in 50ms
106 timing stage:runTopLevelLifecycles Completed in 5505ms
107 verbose stack Error: node-calls-python@1.4.0 install: `node-gyp rebuild`
107 verbose stack Exit status 1
107 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
107 verbose stack     at EventEmitter.emit (events.js:315:20)
107 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
107 verbose stack     at ChildProcess.emit (events.js:315:20)
107 verbose stack     at maybeClose (internal/child_process.js:1021:16)
107 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
108 verbose pkgid node-calls-python@1.4.0
109 verbose cwd /usr/local/lib
110 verbose Linux 5.4.51-v7+
111 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "homebridge-rpi-rf-switch@latest"
112 verbose node v12.18.3
113 verbose npm  v6.14.6
114 error code ELIFECYCLE
115 error errno 1
116 error node-calls-python@1.4.0 install: `node-gyp rebuild`
116 error Exit status 1
117 error Failed at the node-calls-python@1.4.0 install script.
117 error This is probably not a problem with npm. There is likely additional logging output above.
118 verbose exit [ 1, true ]
`

**Comment by Sunoo** [comment]
Interesting, not sure why that's happening if you have Python 3 installed. What does `python3-config --libs` return?

**Comment by shebet** [comment]
Thanks for the tip! there was no Python3-config when I checked. I realised I need to install python3-dev package. I am using Homebridge ready image from their Github page. I assumed it should have python3-dev installed.
Now it installed with no problem.

**Comment by Sunoo** [comment]
Great, good to know. I'll probably add a note to the readme about that.
